ExperimentConfiguration:
  project_root: "/home/robert_kelevra/Projects/bacteria_biology/experiments_folder/experiment_1"
  dataset_folder: "/home/robert_kelevra/Projects/bacteria_biology/utilities/ultrasound_dataset/preprocessed_512_KAR"
  information_dump: 500
  weight_saving_iterations: 2000
  number_iterations: 1e6
  learning_rate: 2.0e-4
  loss: "focal_loss"
  dtype: "float32"
  batch_size: 8
  compute_validation_iteration: True
  resume_training: True

UnetConfiguration:
  input_channels: 1
  output_channels: 1
  convolution_blocks:
    {
     "1": [1, 32],
     "2": [2, 32],
     "3": [4, 64],
     "4": [4, 64],
     "5": [6, 128],
     "6": [6, 128]
    }

