ExperimentConfiguration:
  data_folder: "/home/robert_kelevra/Data/protein_project/protein_data/openfold_data"
  dataset_folder: "/home/robert_kelevra/Data/protein_project/protein_experiments"
  information_dump: 500
  weight_saving_iterations: 2000
  number_iterations: 1e6
  learning_rate: 2.0e-4
  loss: "focal_loss"

UnetConfiguration:
  convolution_blocks:
    {
     "1": [1, 32],
     "2": [2, 32],
     "3": [4, 64],
     "4": [4, 64],
     "5": [6, 128],
     "6": [6, 128]
    }

