ExperimentConfiguration:
  project_root: "/home/robert_kelevra/Projects/image_semantic_segmentation/experiments_folder/experiment_3"
  dataset_folder: "/home/robert_kelevra/Projects/image_semantic_segmentation/ultrasound_dataset/preprocessed_384_KAR"
  expected_input_size: 384
  information_dump: 5
  weight_saving_iterations: 10
  number_iterations: 1e6
  learning_rate: 2.0e-4
  loss: "focal" # Choose either "classic" for classic cross entropy loss or "focal" for focal loss
  focal_loss_parameters:
    alpha: [ 1.0, 2.0, 1.0, 2.0, 1.0 ]
    gamma: 0.75
  dtype: "float32"
  batch_size: 8
  compute_validation_iteration: True
  resume_training: True
  label_dictionary:
    background: 0
    tumor: 1
    mask_square: 2
    mask_b: 3
    mask_plus: 4

UnetConfiguration:
  input_channels: 1
  output_channels: 5
  convolution_blocks:
    {
     "1": [1, 32],
     "2": [2, 32],
     "3": [4, 64],
     "4": [4, 64],
     "5": [6, 128],
     "6": [6, 128]
    }

